import { useState, type ReactNode } from 'react';
import { LazyMotion, domAnimation, m, useReducedMotion } from 'framer-motion';
import Navigation, { Brand } from './Navigation';
import Contact from './Contact';
import FeaturedProjects from './FeaturedProjects';
import { Icon } from './Icons';
import { brands, company, industries, services, whatsappLink } from './content';
import './corporate.css';

export function Reveal({ children, className = '', delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const reduced = useReducedMotion();
  return <m.div className={className} initial={reduced ? false : { opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.08 }} transition={{ duration: 0.6, delay: reduced ? 0 : delay, ease: [0.22, 1, 0.36, 1] }}>{children}</m.div>;
}
function Hero() {
  return <section className="hero section-inner" aria-labelledby="hero-title">
    <div className="hero-copy"><Reveal><p className="eyebrow"><span/>YOUR PARTNER IN INDUSTRIAL PROGRESS</p><h1 id="hero-title">The power<br/>behind your<br/><em>next big move.</em></h1><p className="hero-description">Industrial expertise. Dependable supply.<br/>Electrical and power solutions that move your business forward — from a team that puts your needs first.</p><div className="hero-actions"><a className="button button-maroon" href="#contact">Discuss your requirement <Icon name="diagonal" size={19}/></a><a className="text-link" href="#expertise">Explore our expertise <Icon name="arrow" size={19}/></a></div></Reveal>
      <div className="hero-footnote"><span className="local-dot"/><span>BASED IN LAHORE. BUILT AROUND YOU.</span><span className="hero-line"/></div>
    </div>
    <div className="hero-visual"><img className="hero-photo" src="/company/industry.webp" srcSet="/company/industry-small.webp 800w, /company/industry.webp 1500w" sizes="(max-width: 767px) 100vw, 52vw" alt="Steel structures and equipment inside an industrial production facility" width="1500" height="998" fetchPriority="high"/>
      <div className="photo-grain"/><div className="hero-visual-top"><span><span className="signal-dot"/> SUPPLY. INSTALL. SUPPORT.</span><Icon name="globe" size={22}/></div>
      <div className="hero-photo-caption"><span>ENGINEERED AROUND<br/><strong>what comes next.</strong></span><a href="#expertise" className="round-link" aria-label="Explore our capabilities"><Icon name="diagonal" size={25}/></a></div>
      <div className="hero-trust-card"><span className="trust-icon"><Icon name="power" size={27}/></span><div><strong>One partner.<br/>Complete possibilities.</strong><small>FROM COMPONENTS TO COMMISSIONING</small></div></div>
      <span className="image-index">01 — INDUSTRIAL POSSIBILITIES</span>
    </div>
  </section>;
}
function BrandStrip() {
  return <section className="brand-section" aria-label="Brands we source"><div className="section-inner"><div className="brand-intro"><span className="eyebrow">QUALITY STARTS AT THE SOURCE</span><span>Products from established industry names.</span></div><div className="brand-list">{brands.map((brand,i) => <span className={`manufacturer manufacturer-${i}`} key={brand}>{brand}</span>)}</div></div></section>;
}
function Expertise() {
  return <section className="expertise section-space section-inner" id="expertise" tabIndex={-1}><Reveal className="section-heading"><div><p className="eyebrow"><span/>OUR EXPERTISE</p><h2>Every connection.<br/><em>Considered.</em></h2></div><p className="section-description">The right product. The right technical support.<br/>A complete approach to your electrical, industrial, and power requirements.</p></Reveal><div className="service-grid">{services.map((service,i) => <Reveal key={service.title} delay={(i%3)*0.06}><a className="service-card" href="#contact"><div className="service-card-top"><span className="service-icon"><Icon name={service.icon} size={30}/></span><span className="service-index">0{i+1}</span></div><h3>{service.title}</h3><p>{service.description}</p><div className="service-tags">{service.tags.map(tag=><span key={tag}>{tag}</span>)}</div><span className="service-arrow" aria-hidden="true"><Icon name="diagonal" size={19}/></span></a></Reveal>)}</div></section>;
}
function About() {
  return <section className="about-section section-space" id="about" tabIndex={-1}><div className="section-inner about-grid"><Reveal className="about-art"><div className="about-grid-lines"/><div className="about-orbit orbit-one"/><div className="about-orbit orbit-two"/><div className="about-emblem"><img src="/HST_logo.png" alt="HST Enterprises wing emblem" width="245" height="185"/></div><span className="about-coordinate top-left">HST / LAHORE</span><span className="about-coordinate bottom-right">PAKISTAN</span><div className="about-art-text">LOCAL ROOTS.<br/><strong>Lasting connections.</strong></div><span className="about-art-pill"><Icon name="check" size={15}/> INTEGRITY IN EVERY INTERACTION</span></Reveal>
      <Reveal className="about-copy"><p className="eyebrow"><span/>THE PEOPLE BEHIND THE POWER</p><h2>More than a supplier.<br/><em>Your next partner.</em></h2><p className="about-lead">Good business starts with understanding what you need.</p><p>Based in Lahore, HST Enterprises brings together industrial supply and practical technical expertise. We work with manufacturers, contractors, traders, and facility teams to find the right solution at a competitive price.</p><p>Our ambition is simple: support the growth of your business through quality products, dependable service, and relationships built to last.</p><div className="about-values"><span><Icon name="check" size={17}/> Quality, without shortcuts</span><span><Icon name="check" size={17}/> A customer-first approach</span><span><Icon name="check" size={17}/> Long-term thinking</span></div><a href="#contact" className="text-link">Meet your supply partner <Icon name="arrow" size={19}/></a></Reveal></div></section>;
}
function Industries() {
  const [active, setActive] = useState(0);
  const current = industries[active];
  return <section className="industries-section section-space" id="industries" tabIndex={-1}><div className="section-inner"><Reveal className="section-heading"><div><p className="eyebrow"><span/>BUILT FOR YOUR WORLD</p><h2>Behind the places<br/>that <em>never stand still.</em></h2></div><p className="section-description">Different industries. Different demands.<br/>The same commitment to getting it right.</p></Reveal><div className="industry-tabs" role="tablist" aria-label="Industries we serve">{industries.map((industry,i)=><button role="tab" aria-selected={i===active} aria-controls={`industry-panel-${i}`} id={`industry-tab-${i}`} tabIndex={i===active?0:-1} key={industry.name} onClick={()=>setActive(i)} onKeyDown={e=>{let next=i; if(e.key==='ArrowRight')next=(i+1)%industries.length; else if(e.key==='ArrowLeft')next=(i-1+industries.length)%industries.length; else if(e.key==='Home')next=0; else if(e.key==='End')next=industries.length-1; else return; e.preventDefault();setActive(next);document.getElementById(`industry-tab-${next}`)?.focus();}}>{industry.name}<span>0{i+1}</span></button>)}</div>
      <div className="industry-panel" role="tabpanel" id={`industry-panel-${active}`} aria-labelledby={`industry-tab-${active}`} tabIndex={0}><div className="industry-image"><img src="/company/power.webp" alt="Electrical equipment and power distribution infrastructure" loading="lazy" width="1100" height="733"/><span className="image-caption">THE INFRASTRUCTURE BEHIND POSSIBILITY</span></div><div className="industry-detail" key={active}><span className="industry-number">0{active+1} / {current.name.toUpperCase()}</span><h3>{current.title}</h3><p>{current.copy}</p><ul>{current.items.map(item=><li key={item}><Icon name="check" size={17}/>{item}</li>)}</ul><a href="#contact" className="text-link light-link">Talk about your industry <Icon name="arrow" size={19}/></a></div></div></div></section>;
}
function Process() {
  return <section className="process-section section-space section-inner"><Reveal className="section-heading"><div><p className="eyebrow"><span/>A CLEAR WAY FORWARD</p><h2>Complex requirements.<br/><em>Simple conversations.</em></h2></div><a href="#contact" className="text-link">Start with your requirement <Icon name="diagonal" size={19}/></a></Reveal><div className="process-grid">{[
    ['01','We listen.','Tell us about your application, specifications, quantities, and timelines. We start with what matters to you.'],
    ['02','We find the fit.','We work through the appropriate products or services and prepare a clear quotation for your review.'],
    ['03','We move forward.','Once the scope is agreed, we coordinate supply or service and stay connected through the next steps.'],
  ].map(([number,title,copy])=><Reveal key={number} className="process-step"><span className="process-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div></Reveal>)}</div></section>;
}
function Footer() {
  return <footer className="corporate-footer"><div className="section-inner"><div className="footer-main"><div><Brand light/><p>Importer. General order supplier.<br/>Contractor & services.<br/><span>Power for your trust.</span></p></div><div className="footer-links"><p className="footer-label">EXPLORE</p><a href="#projects">Featured projects</a><a href="#expertise">Our expertise</a><a href="#about">About HST</a><a href="#industries">Industries we serve</a><a href="#contact">Get in touch</a></div><div className="footer-links"><p className="footer-label">LET’S CONNECT</p><a href={`tel:+${company.whatsapp}`}>{company.phone}</a><a href="tel:+924237664202">{company.telephone}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href={whatsappLink()} target="_blank" rel="noreferrer">Chat on WhatsApp <Icon name="diagonal" size={15}/></a></div><div className="footer-portal"><Icon name="portal" size={24}/><h3>Your work.<br/>One workspace.</h3><a href="/portal">Employee portal <Icon name="arrow" size={18}/></a><small>Private access for the HST team.</small></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} HST Enterprises. All rights reserved.</span><span>Lahore, Pakistan <span className="footer-dot">•</span> Built on trust.</span></div></div></footer>;
}
export default function CorporateSite() {
  return <LazyMotion features={domAnimation}><div className="corporate"><a className="skip-link" href="#main-content">Skip to content</a><div className="utility-bar"><div className="section-inner"><span>IMPORTER, GENERAL ORDER SUPPLIER, CONTRACTOR & SERVICES</span><a href="tel:+924237664202"><Icon name="phone" size={12}/> +92 42 37664202</a></div></div><Navigation/><main id="main-content" tabIndex={-1}><Hero/><BrandStrip/><FeaturedProjects/><Expertise/><About/><Industries/><Process/><Contact/></main><Footer/><a className="floating-whatsapp" href={whatsappLink()} target="_blank" rel="noreferrer" aria-label="Chat with HST Enterprises on WhatsApp"><Icon name="whatsapp" size={27}/><span>Let’s talk</span><span className="whatsapp-notification"/></a></div></LazyMotion>;
}
